<a href="https://colab.research.google.com/github/oburckard/MyRepo/blob/master/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

x² + y² + z² = 2
<=> x² + y² + z² - 2 = 0

x² + y²  = 1
<=> x² + y²  - 1 = 0

x² = y
<=> x² - y = 0


The Jacobian matrix is 
J(x,y)=(2x   2y   2z)
       (2x   2y   0 )
       (2x   -1   0 )

In [0]:
import numpy as np

##LAB EXERCISE##

def function_lab(xyz):
  x, y, z = xyz
  return [x**2 + y**2 + z**2 -2, x**2 + y**2 -1, x**2 - y]

def jacobian_lab(xyz):
  x, y, z = xyz
  return [[2*x, 2*y, 2*z],
          [2*x, 2*y, 0],
          [2*x, -1, 0]]



# Example:

def jacobian_example(xy):
    x, y = xy
    return [[1, 2],
            [2*x, 8*y]]

def function_example(xy):
    x, y = xy
    return [x + 2*y - 2, x**2 + 4*y**2 - 4]




# Another  exercise:
def function_exercise(xyz):
    x, y, z = xyz
    return [x + y + z - 3,
            x**2 + y**2 + z**2 - 5,
            np.exp(x) + x*y - x*z - 1]

def jacobian_exercise(xyz):
    x, y, z = xyz
    return [[1, 1, 1],
            [2*x, 2*y, 2*z],
            [np.exp(x) + y - z, x, -x]]

# slow convergence
def jacobian_slow(xy):
    x, y = xy
    return [[2*x, 2*y],
            [1, 1]]

def function_slow(xy):
    x, y = xy
    return [x**2 + y**2 - 0.0000000000001, x + y ]

    
# iterative Newton's method
def iterative_newton(fun, x_init, jacobian):
    max_iter = 50
    epsilon = 1e-8

    x_last = x_init

    for k in range(max_iter):
        # Solve J(xn)*( xn+1 - xn ) = -F(xn):
        J = np.array(jacobian(x_last))
        F = np.array(fun(x_last))


        # inverted Jacobian
        Jinv = np.linalg.inv(J)
        #  x(n+1) = x(n) − J^(−1)(x(n))*F(x(n)).
        #  np.dot - array/vector multiplication
        diff = np.dot(Jinv,F)
        x_last = x_last - diff
        
        print(x_last)        

        # Stop condition:
        if np.linalg.norm(diff) < epsilon:
            print('convergence!, nre iter:', k )
            break

    else: # only if the for loop end 'naturally'
        print('not converged')

    return x_last





# slightly different implementation solving a set of linear equations
def iterative_newton_v2(fun, x_init, jacobian):
    max_iter = 50
    epsilon = 1e-8

    x_last = x_init

    for k in range(max_iter):
        # Solve J(xn)*( xn+1 - xn ) = -F(xn):
        J = np.array(jacobian(x_last))
        F = np.array(fun(x_last))

        diff = np.linalg.solve( J, -F )
        x_last = x_last + diff

        # Stop condition:
        if np.linalg.norm(diff) < epsilon:
            print('convergence!, nre iter:', k )
            break

    else: # only if the for loop end 'naturally'
        print('not converged')

    return x_last



# For the exercice:
x_sol = iterative_newton(function_exercise, [2.0,1.0,2.0], jacobian_exercise)
print('solution exercice:', x_sol )
print('F(sol)', function_exercise(x_sol) )
print(" ")

# second version
x_sol = iterative_newton_v2(function_exercise, [2.0,1.0,2.0], jacobian_exercise)
print('solution exercise:', x_sol )
print('F(sol)', function_exercise(x_sol) )
print(" ")

# slow convergence
x_sol = iterative_newton(function_slow, [2.0,1.0], jacobian_slow)
print('solution slow:', x_sol )
print('F(sol)', function_slow(x_sol) )
print(" ")

# second version
x_sol = iterative_newton_v2(function_slow, [2.0,1.0], jacobian_slow)
print('solution slow:', x_sol )
print('F(sol)', function_slow(x_sol) )
print(" ")

# For the example:
x_sol = iterative_newton(function_example, [1.0,2.0], jacobian_example)
print('solution example:', x_sol )
print( function_example(x_sol) )

# second version
x_sol = iterative_newton_v2(function_example, [1.0,2.0], jacobian_example)
print('solution example:', x_sol )
print( function_example(x_sol) )

#For the lab
x_sol = iterative_newton(function_lab, [2.0,1.0,2.0], jacobian_lab)
print('solution lab:', x_sol )
print( function_lab(x_sol) )

# second version
x_sol = iterative_newton_v2(function_lab, [2.0,1.0,2.0], jacobian_lab)
print('solution lab:', x_sol )
print( function_lab(x_sol) )

[ 1.95362338 -1.          2.04637662]
[ 1.49651235 -0.32885865  1.83234629]
[ 1.28066846 -0.13217078  1.85150232]
[ 1.2279083  -0.09540156  1.86749326]
[ 1.22440996 -0.09314308  1.86873313]
[ 1.22439432 -0.09313314  1.86873882]
[ 1.22439432 -0.09313314  1.86873882]
convergence!, nre iter: 6
solution exercice: [ 1.22439432 -0.09313314  1.86873882]
F(sol) [0.0, 0.0, 0.0]
 
convergence!, nre iter: 6
solution exercise: [ 1.22439432 -0.09313314  1.86873882]
F(sol) [0.0, 0.0, -4.440892098500626e-16]
 
[ 2.5 -2.5]
[ 1.25 -1.25]
[ 0.625 -0.625]
[ 0.3125 -0.3125]
[ 0.15625 -0.15625]
[ 0.078125 -0.078125]
[ 0.0390625 -0.0390625]
[ 0.01953125 -0.01953125]
[ 0.00976563 -0.00976563]
[ 0.00488281 -0.00488281]
[ 0.00244141 -0.00244141]
[ 0.0012207 -0.0012207]
[ 0.00061035 -0.00061035]
[ 0.00030518 -0.00030518]
[ 0.00015259 -0.00015259]
[ 7.62941638e-05 -7.62941638e-05]
[ 3.81474096e-05 -3.81474096e-05]
[ 1.90743601e-05 -1.90743601e-05]
[ 9.53849073e-06 -9.53849073e-06]
[ 4.77186632e-06 -4.77186632e-0

In [29]:
import numpy as np

#####AITKEN 1 DIMENSION #####

def function_f(x):
  return 1/x-0.5

def function_g(x):
  return x+(1/16)*function_f(x)


def aitken(x0,e,nmax):

  nbEval = 0
  flag = 1
  step =1
  
  condition = True
  while condition:
    x1 = function_g(x0)
    x2 = function_g(x1)
    
    if x2-2*x1+x0 == 0.0:
      print('Divide by zero error!')
      break

    x0 = x0-(x1-x0)**2/(x2-2*x1+x0)
        
    nbEval = nbEval+2
    step = step + 1

    condition1 = step<nmax
    condition2 = abs(function_f(x0))>e
    condition = condition1 and condition2


  if flag==1:
    print('\nRequired root is: %0.8f' % x0)
    print('Number of evaluation of g is: %0.8f ' % nbEval)
  else:
    print('\nNot Convergent.')
      

# Input Section
#x0 = input('Enter Guess: ')
#e = input('Tolerable Error: ')
#nmax = input('Maximum Step: ')
x0 = 1.5
e =0.000001
nmax=20

# Converting x0 and e to float
x0 = float(x0)
e = float(e)

# Converting N to integer
nmax = int(nmax)

# Starting Newton Method
aitken(x0,e,nmax)








  


Required root is: 2.00000000
Number of evaluation of g is: 8.00000000 


In [0]:
import numpy as np

##### AITKEN MANY DIMENSIONS ######

def function_slow(xy):
    x, y = xy
    return [x**2 + y**2 - 0.0000000000001, x + y ]

    

